### ISSUE TITLE
Regional Proxy Issue

### ISSUE THREAD

**Issue by Sethtrosity** [stuartmackenzie/falcoqb#3]
Seems like using proxies cross region causes the links to be formatted incorrectly region wise.

`https://www.amd.com/en/direct-buy/us?queueittoken=e_eu193hd648~q_edc71188-123b-4824-b9bb-b5dc80c192dd~ts_1643900987~ce_true~rt_queue~ti_0a20c0a1-713c-41bd-bd9d-40b8cb42f292~hip_1c2a21a5622fce9f603357acce8e5e23e4b8d28f82255a35ad5e036e522ddc02~h_2c3c02bb44bbfbc37b8f23e824fbe1410cda3d7e48fb7eaa4c0647e30b404839`

I assume this was EU event using US proxies. Beginning URL is the US store, and user wasn't sent to EU page.

**Comment by frysee** [comment]
Wrong. This was DE proxy for EU event. Link eventually passed queue but ended on an empty QueueIT page instead of redirecting on store. Had two of those.

Falco actually always produced links formatted that way the last weeks, and those always worked perfectly. Not sure if something changed that would maybe now require the region to be correct in the URL?

**Comment by Sethtrosity** [comment]
@frysee Ah I see, well good thing you added the correct details. Maybe it is another issue altogether then. Pat did say you shouldn't have a problem using proxies from a different region.
